version: "3.8"
services:
  web:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
    environment:
      - "REDIS_URL='redis://db:6379/15'"
  db:
    image: redis:6.0.3-alpine3.11
    expose:
      - "6379"
